# 1. FIX COLORS: Ensure Ghostty looks pretty and modern
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# 2. ENABLE MOUSE: Click to select panes, drag to resize, scroll with wheel
set -g mouse on


# Window Index starting at 1
set -g base-index 1
setw -g pane-base-index 1

# 3. BETTER PREFIX: Ctrl+b is a finger stretch. Ctrl+a is standard.
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g pane-border-style 'fg=#364A4A'
set -g pane-active-border-style 'fg=#39CBA3'
set -g status-left-length 50
set -g status-style 'bg=#1e1e2e fg=#54C7CF'

# 4. INTUITIVE SPLITS: Use | for vertical and - for horizontal
# Also opens new panes in the CURRENT directory, not the home directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# 5. VIM NAVIGATION: Move between panes with h/j/k/l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 6. RELOAD CONFIG: Press Prefix + r to apply changes immediately
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# 1. Sessionizer: Ctrl + f
# Safe for you since you scroll with Ctrl+d/u
bind-key -n C-f display-popup -E -w 60% -h 80% -b rounded -T " Projects " "~/.config/tmux/scripts/sessionizer"

bind-key -n C-S-d display-popup -E -w 70% -h 60% -b rounded -T " Kill Session " "~/.config/tmux/scripts/kill-session"


# 2. Session List: Leader + s
bind-key s choose-tree -sZ


bind -n M-1 if-shell 'tmux select-window -t 1' '' 'new-window -t 1'
bind -n M-2 if-shell 'tmux select-window -t 2' '' 'new-window -t 2'
bind -n M-3 if-shell 'tmux select-window -t 3' '' 'new-window -t 3'
bind -n M-4 if-shell 'tmux select-window -t 4' '' 'new-window -t 4'
bind -n M-5 if-shell 'tmux select-window -t 5' '' 'new-window -t 5'
bind -n M-6 if-shell 'tmux select-window -t 6' '' 'new-window -t 6'
bind -n M-7 if-shell 'tmux select-window -t 7' '' 'new-window -t 7'
bind -n M-8 if-shell 'tmux select-window -t 8' '' 'new-window -t 8'
bind -n M-9 if-shell 'tmux select-window -t 9' '' 'new-window -t 9'
bind -n M-0 if-shell 'tmux select-window -t 10' '' 'new-window -t 10'

bind-key -n M-h run-shell "~/.config/tmux/scripts/tmux-default"

bind-key -n C-w run-shell "~/.config/tmux/scripts/ensure-workers"


set -g extended-keys on
set -g extended-keys-format csi-u
